# Generated by Django 2.0.6 on 2018-06-26 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBookmark',
            fields=[
                ('bookmark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookmark.Bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('bookmark.bookmark',),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='location_folder',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_type',
            field=models.CharField(choices=[('u', 'url'), ('f', 'folder')], default='u', max_length=6),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default='', editable=False),
        ),
    ]
