# Generated by Django 2.0.6 on 2018-06-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20180626_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
